export type InvoiceStatus = 'Draft' | 'Open' | 'Overdue' | 'Paid' | 'Partially Paid'

export interface SourceContract {
  no: string
  title: string
  price: number
}

export interface AdjustmentRecord {
  type: 'Deduct Payment' | 'Additional Payment'
  reason: string
  amount: number
}

export interface PaymentRecord {
  date: string
  transactionRef: string
  method: string
  bankAccount: string
  amount: number
}

export interface TripRecord {
  activeDays: string
  startTime: string
  description: string
  capacity: number
  tripPrice: number
}

export interface OtherChargeRecord {
  description: string
  quantity: number
  unitPrice: number
  amount: number
}

export interface ContractLineItem {
  contractNo: string
  title: string
  trips: TripRecord[]
  tripsSubtotal: number
  otherCharges: OtherChargeRecord[]
  otherChargesSubtotal: number
  subTotal: number
  discount: number
  surcharge: number
  total: number
}

export interface Invoice {
  id: string
  invoiceNo: string
  customerCode: string
  contractTitles: string[]
  dueDate: string
  status: InvoiceStatus
  lastUpdatedOn: string
  lastUpdatedAgo: string
  contractGroup: string
  invoiceDate: string
  paymentTerms: string
  purchaseOrder: string
  billingCompany: string
  accountPayable: string
  subTotal: number
  adjustment: number
  gst: number
  grandTotal: number
  amountReceived: number
  outstandingBalance: number
  billingCompanyName: string
  attention: string
  email: string
  emailCc: string
  sourceContracts: SourceContract[]
  contractDetails: ContractLineItem[]
  adjustments: AdjustmentRecord[]
  payments: PaymentRecord[]
  createdOn: string
  createdBy: string
  lastUpdatedBy: string
}

const defaultTrips: TripRecord[] = [
  { activeDays: 'Every 4 weeks - Week 1 | Mon, Sat · Week 2 | Tue, Fri', startTime: '08:30 AM', description: 'Trip for NUS new student on graduation', capacity: 10, tripPrice: 5000 },
  { activeDays: 'Every 4 weeks - Week 1 | Mon, Sat · Week 2 | Tue, Fri', startTime: '08:30 AM', description: 'Trip for NUS new student on graduation', capacity: 20, tripPrice: 5000 },
  { activeDays: 'Every 4 weeks - Week 1 | Mon, Sat · Week 2 | Tue, Fri', startTime: '08:30 AM', description: 'Big trip for Singapore open government center', capacity: 30, tripPrice: 5000 },
  { activeDays: 'Every 4 weeks - Week 1 | Mon, Sat · Week 2 | Tue, Fri', startTime: '08:30 AM', description: 'Big trip for Singapore open government center', capacity: 10, tripPrice: 1000 },
  { activeDays: 'Every 4 weeks - Week 1 | Mon, Sat · Week 2 | Tue, Fri', startTime: '08:30 AM', description: 'sample trip description', capacity: 15, tripPrice: 4000 },
]

const defaultOtherCharges: OtherChargeRecord[] = [
  { description: 'Extra Charges Service Fee', quantity: 1, unitPrice: 300, amount: 300 },
  { description: 'Extra Charges Maintenance Fee', quantity: 1, unitPrice: 400, amount: 400 },
  { description: 'Driver Retribution', quantity: 2, unitPrice: 5, amount: 10 },
  { description: 'Security Pack', quantity: 1, unitPrice: 9, amount: 9 },
  { description: 'Extra Wheels', quantity: 1, unitPrice: 149, amount: 149 },
  { description: 'Extra Wheels', quantity: 2, unitPrice: 149, amount: 249 },
]

const defaultAdjustments: AdjustmentRecord[] = [
  { type: 'Deduct Payment', reason: 'This is dummy date of reason for adjustment', amount: 300 },
  { type: 'Additional Payment', reason: 'This is dummy date of reason for adjustment', amount: 400 },
  { type: 'Deduct Payment', reason: 'This is dummy date of reason for adjustment', amount: 5 },
  { type: 'Deduct Payment', reason: 'This is dummy date of reason for adjustment', amount: 9 },
  { type: 'Deduct Payment', reason: 'This is dummy date of reason for adjustment', amount: 140 },
  { type: 'Additional Payment', reason: 'no adjustments have been made to this invoice', amount: 140 },
]

const defaultPayments: PaymentRecord[] = [
  { date: '14 Jan 2026', transactionRef: 'TRF-00124', method: 'Bank Transfer', bankAccount: 'Jim Cun Lee - HSBC', amount: 5012 },
  { date: '14 Mar 2026', transactionRef: 'TRF-0012-S', method: 'Bank Transfer', bankAccount: 'Jim Cun Lee - HSBC', amount: 4100 },
  { date: '20 Apr 2026', transactionRef: 'BHSL-0431022', method: 'Bank Transfer', bankAccount: 'Monica - DBS', amount: 5500 },
  { date: '10 Jun 2026', transactionRef: 'INV-924124', method: 'Bank Transfer', bankAccount: 'Monica - DBS', amount: 10000 },
  { date: '21 Jan 2026', transactionRef: 'FRIS-92411', method: 'Bank Transfer', bankAccount: 'Monica - DBS', amount: 8600 },
]

function makeContractDetail(contractNo: string, title: string): ContractLineItem {
  return {
    contractNo,
    title,
    trips: defaultTrips,
    tripsSubtotal: 16500,
    otherCharges: defaultOtherCharges,
    otherChargesSubtotal: 5000,
    subTotal: 96200,
    discount: 100,
    surcharge: 300,
    total: 99000,
  }
}

export const INVOICES: Invoice[] = [
  {
    id: '1',
    invoiceNo: 'ATA-2026-0015',
    customerCode: 'CUST-0042',
    contractTitles: ['Airport Shuttle Service - Terminal 1 & 2', 'Airport Shuttle Service - Terminal 3', 'Airport Shuttle - Park Area'],
    dueDate: '28 Jun 2026',
    status: 'Draft',
    lastUpdatedOn: '19 Mar 2026',
    lastUpdatedAgo: '3 months ago',
    contractGroup: 'Westpoint',
    invoiceDate: '1 Apr 2026',
    paymentTerms: '30 Days',
    purchaseOrder: '-',
    billingCompany: 'Westpoint Rapid',
    accountPayable: 'DBS',
    subTotal: 1000,
    adjustment: 100,
    gst: 99,
    grandTotal: 1199,
    amountReceived: 99,
    outstandingBalance: 1100,
    billingCompanyName: 'APL Shipyard',
    attention: 'Long Chin Kim',
    email: 'Long@apl.com',
    emailCc: 'sales@apl.com',
    sourceContracts: [
      { no: 'CC-2026-0089', title: 'Airport Shuttle - Terminal 1 & 2', price: 5000 },
      { no: 'CC-2026-0099', title: 'Airport Shuttle - Terminal 3', price: 5000 },
      { no: 'CC-2026-0100', title: 'Airport Shuttle - Park Area', price: 5000 },
    ],
    contractDetails: [
      makeContractDetail('CC-2024-29122484', 'Transportation Agreement with NUS - Summer Period'),
      makeContractDetail('CC-2024-50021222', 'Airport Shuttle Agreement - Terminal 1 & 2'),
      makeContractDetail('CC-2024-29121234', 'Airport Shuttle Agreement - Terminal 3'),
      makeContractDetail('CC-2024-24000012', 'Airport Shuttle Agreement - Park Area'),
      makeContractDetail('CC-2024-29122485', 'Airport Shuttle Agreement - Budget Terminal'),
    ],
    adjustments: defaultAdjustments,
    payments: defaultPayments,
    createdOn: '27 Sep 2025, 2:03pm',
    createdBy: 'System',
    lastUpdatedBy: 'Deve Tano',
  },
  {
    id: '2',
    invoiceNo: 'ATA-2026-0014',
    customerCode: 'CUST-0038',
    contractTitles: ['Employee Transport - Morning Shift Route A', 'Employee Transport - Night Shift Route A'],
    dueDate: '25 Jun 2026',
    status: 'Draft',
    lastUpdatedOn: '28 May 2026',
    lastUpdatedAgo: '13 days ago',
    contractGroup: 'Greenfield',
    invoiceDate: '10 May 2026',
    paymentTerms: '30 Days',
    purchaseOrder: 'PO-2026-114',
    billingCompany: 'Greenfield Corp',
    accountPayable: 'OCBC',
    subTotal: 8000,
    adjustment: 0,
    gst: 640,
    grandTotal: 8640,
    amountReceived: 0,
    outstandingBalance: 8640,
    billingCompanyName: 'Greenfield Industries',
    attention: 'Sarah Wong',
    email: 'sarah.wong@greenfield.com',
    emailCc: 'finance@greenfield.com',
    sourceContracts: [
      { no: 'CC-2026-0041', title: 'Employee Transport - Morning Shift Route A', price: 4000 },
      { no: 'CC-2026-0042', title: 'Employee Transport - Night Shift Route A', price: 4000 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0041', 'Employee Transport - Morning Shift Route A')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '28 May 2026, 9:15am',
    createdBy: 'System',
    lastUpdatedBy: 'Jasmine Tan',
  },
  {
    id: '3',
    invoiceNo: 'WTA-2026-0012',
    customerCode: 'CUST-0015',
    contractTitles: ['School Bus Service - Greenfield International School'],
    dueDate: '20 Jun 2026',
    status: 'Open',
    lastUpdatedOn: '20 Nov 2025',
    lastUpdatedAgo: '7 months ago',
    contractGroup: 'Greenfield',
    invoiceDate: '1 Nov 2025',
    paymentTerms: '45 Days',
    purchaseOrder: 'PO-2025-887',
    billingCompany: 'Greenfield Academy',
    accountPayable: 'UOB',
    subTotal: 12000,
    adjustment: 200,
    gst: 936,
    grandTotal: 13136,
    amountReceived: 0,
    outstandingBalance: 13136,
    billingCompanyName: 'Greenfield International School',
    attention: 'Principal Lee',
    email: 'principal@greenfield.edu.sg',
    emailCc: 'admin@greenfield.edu.sg',
    sourceContracts: [
      { no: 'CC-2025-0331', title: 'School Bus Service - Morning Route', price: 6000 },
      { no: 'CC-2025-0332', title: 'School Bus Service - Afternoon Route', price: 6000 },
    ],
    contractDetails: [makeContractDetail('CC-2025-0331', 'School Bus Service - Greenfield International School')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '20 Nov 2025, 10:00am',
    createdBy: 'System',
    lastUpdatedBy: 'Marcus Lim',
  },
  {
    id: '4',
    invoiceNo: 'ATA-2026-0013',
    customerCode: 'CUST-0042',
    contractTitles: ['Airport Shuttle Service - Terminal 3'],
    dueDate: '15 Jun 2026',
    status: 'Open',
    lastUpdatedOn: '14 Mar 2026',
    lastUpdatedAgo: '3 months ago',
    contractGroup: 'Westpoint',
    invoiceDate: '1 Mar 2026',
    paymentTerms: '30 Days',
    purchaseOrder: '-',
    billingCompany: 'Westpoint',
    accountPayable: 'DBS',
    subTotal: 5000,
    adjustment: 0,
    gst: 400,
    grandTotal: 5400,
    amountReceived: 0,
    outstandingBalance: 5400,
    billingCompanyName: 'APL Shipyard',
    attention: 'David Lim',
    email: 'david.lim@apl.com',
    emailCc: 'sales@apl.com',
    sourceContracts: [
      { no: 'CC-2026-0099', title: 'Airport Shuttle - Terminal 3', price: 5000 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0099', 'Airport Shuttle Service - Terminal 3')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '14 Mar 2026, 3:30pm',
    createdBy: 'System',
    lastUpdatedBy: 'Deve Tano',
  },
  {
    id: '5',
    invoiceNo: 'ATA-2026-0011',
    customerCode: 'CUST-0003',
    contractTitles: ['Daily Commuter Route - Jurong East to CBD'],
    dueDate: '08 Jun 2026',
    status: 'Overdue',
    lastUpdatedOn: '1 Jun 2026',
    lastUpdatedAgo: '9 days ago',
    contractGroup: 'Commute Corp',
    invoiceDate: '1 May 2026',
    paymentTerms: '30 Days',
    purchaseOrder: 'PO-2026-203',
    billingCompany: 'Commute Corp',
    accountPayable: 'HSBC',
    subTotal: 3200,
    adjustment: 0,
    gst: 256,
    grandTotal: 3456,
    amountReceived: 0,
    outstandingBalance: 3456,
    billingCompanyName: 'Commute Corp Pte Ltd',
    attention: 'James Tan',
    email: 'james.tan@commutecorp.com',
    emailCc: 'finance@commutecorp.com',
    sourceContracts: [
      { no: 'CC-2026-0077', title: 'Daily Commuter Route - Jurong East to CBD', price: 3200 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0077', 'Daily Commuter Route - Jurong East to CBD')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '1 May 2026, 8:00am',
    createdBy: 'System',
    lastUpdatedBy: 'Jasmine Tan',
  },
  {
    id: '6',
    invoiceNo: 'WRA-2026-0005',
    customerCode: 'CUST-0019',
    contractTitles: ['Weekend Tour Package - Sentosa Island Loop'],
    dueDate: '05 Jun 2026',
    status: 'Overdue',
    lastUpdatedOn: '8 Sep 2025',
    lastUpdatedAgo: '9 months ago',
    contractGroup: 'Sentosa Leisure',
    invoiceDate: '1 Sep 2025',
    paymentTerms: '60 Days',
    purchaseOrder: '-',
    billingCompany: 'Sentosa Corp',
    accountPayable: 'Citibank',
    subTotal: 7500,
    adjustment: 500,
    gst: 640,
    grandTotal: 8640,
    amountReceived: 0,
    outstandingBalance: 8640,
    billingCompanyName: 'Sentosa Leisure Pte Ltd',
    attention: 'Karen Ng',
    email: 'karen@sentosaleisure.com',
    emailCc: 'ops@sentosaleisure.com',
    sourceContracts: [
      { no: 'CC-2025-0188', title: 'Weekend Tour - Sentosa Loop Morning', price: 3750 },
      { no: 'CC-2025-0189', title: 'Weekend Tour - Sentosa Loop Afternoon', price: 3750 },
    ],
    contractDetails: [makeContractDetail('CC-2025-0188', 'Weekend Tour Package - Sentosa Island Loop')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '8 Sep 2025, 2:00pm',
    createdBy: 'System',
    lastUpdatedBy: 'Marcus Lim',
  },
  {
    id: '7',
    invoiceNo: 'ATA-2026-0004',
    customerCode: 'CUST-0003',
    contractTitles: ['Daily Commuter Route - Tampines to Raffles Place'],
    dueDate: '20 May 2026',
    status: 'Overdue',
    lastUpdatedOn: '5 Jan 2026',
    lastUpdatedAgo: '5 months ago',
    contractGroup: 'Commute Corp',
    invoiceDate: '1 Jan 2026',
    paymentTerms: '30 Days',
    purchaseOrder: 'PO-2026-011',
    billingCompany: 'Commute Corp',
    accountPayable: 'HSBC',
    subTotal: 4100,
    adjustment: 0,
    gst: 328,
    grandTotal: 4428,
    amountReceived: 0,
    outstandingBalance: 4428,
    billingCompanyName: 'Commute Corp Pte Ltd',
    attention: 'James Tan',
    email: 'james.tan@commutecorp.com',
    emailCc: 'finance@commutecorp.com',
    sourceContracts: [
      { no: 'CC-2026-0012', title: 'Daily Commuter Route - Tampines to Raffles Place', price: 4100 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0012', 'Daily Commuter Route - Tampines to Raffles Place')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '5 Jan 2026, 9:00am',
    createdBy: 'System',
    lastUpdatedBy: 'Jasmine Tan',
  },
  {
    id: '8',
    invoiceNo: 'ATA-2026-0002',
    customerCode: 'CUST-0008',
    contractTitles: ['Hotel Guest Shuttle - Orchard Road Circuit'],
    dueDate: '10 May 2026',
    status: 'Paid',
    lastUpdatedOn: '17 Feb 2026',
    lastUpdatedAgo: '4 months ago',
    contractGroup: 'Orchard Hotels',
    invoiceDate: '15 Jan 2026',
    paymentTerms: '30 Days',
    purchaseOrder: 'PO-2026-049',
    billingCompany: 'Orchard Hotels Ltd',
    accountPayable: 'Standard Chartered',
    subTotal: 6200,
    adjustment: 0,
    gst: 496,
    grandTotal: 6696,
    amountReceived: 6696,
    outstandingBalance: 0,
    billingCompanyName: 'Orchard Hotels Ltd',
    attention: 'Rachel Chen',
    email: 'rachel.chen@orchardhotels.com',
    emailCc: 'concierge@orchardhotels.com',
    sourceContracts: [
      { no: 'CC-2026-0025', title: 'Hotel Guest Shuttle - Orchard Road Circuit', price: 6200 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0025', 'Hotel Guest Shuttle - Orchard Road Circuit')],
    adjustments: [],
    payments: [
      { date: '10 Feb 2026', transactionRef: 'TRF-0201', method: 'Bank Transfer', bankAccount: 'Rachel Chen - SCB', amount: 6696 },
    ],
    createdOn: '17 Feb 2026, 11:00am',
    createdBy: 'System',
    lastUpdatedBy: 'Deve Tano',
  },
  {
    id: '9',
    invoiceNo: 'ATA-2026-0001',
    customerCode: 'CUST-0003',
    contractTitles: ['Daily Commuter Route - Woodlands to Tanjong Pagar'],
    dueDate: '05 May 2026',
    status: 'Paid',
    lastUpdatedOn: '22 Apr 2026',
    lastUpdatedAgo: '7 weeks ago',
    contractGroup: 'Commute Corp',
    invoiceDate: '1 Dec 2025',
    paymentTerms: '30 Days',
    purchaseOrder: '-',
    billingCompany: 'Commute Corp',
    accountPayable: 'HSBC',
    subTotal: 3800,
    adjustment: 0,
    gst: 304,
    grandTotal: 4104,
    amountReceived: 4104,
    outstandingBalance: 0,
    billingCompanyName: 'Commute Corp Pte Ltd',
    attention: 'James Tan',
    email: 'james.tan@commutecorp.com',
    emailCc: 'finance@commutecorp.com',
    sourceContracts: [
      { no: 'CC-2025-0401', title: 'Daily Commuter Route - Woodlands to Tanjong Pagar', price: 3800 },
    ],
    contractDetails: [makeContractDetail('CC-2025-0401', 'Daily Commuter Route - Woodlands to Tanjong Pagar')],
    adjustments: [],
    payments: [
      { date: '20 Apr 2026', transactionRef: 'TRF-0422', method: 'Bank Transfer', bankAccount: 'James Tan - HSBC', amount: 4104 },
    ],
    createdOn: '22 Apr 2026, 8:30am',
    createdBy: 'System',
    lastUpdatedBy: 'Marcus Lim',
  },
  {
    id: '10',
    invoiceNo: 'WCA-2026-0008',
    customerCode: 'CUST-0027',
    contractTitles: ['Corporate Event Transport - Annual Dinner 2026'],
    dueDate: '10 Jun 2026',
    status: 'Partially Paid',
    lastUpdatedOn: '7 Jun 2026',
    lastUpdatedAgo: '3 days ago',
    contractGroup: 'APLSHIPWARD',
    invoiceDate: '20 Jun 2026',
    paymentTerms: '30 Days',
    purchaseOrder: '-',
    billingCompany: 'Westpoint',
    accountPayable: 'DBS',
    subTotal: 6000,
    adjustment: 0,
    gst: 480,
    grandTotal: 6480,
    amountReceived: 600,
    outstandingBalance: 5880,
    billingCompanyName: 'APL Shipyard',
    attention: 'David Lim',
    email: 'david.lim@apl.com',
    emailCc: 'sales@apl.com',
    sourceContracts: [
      { no: 'CC-2026-0089', title: 'Airport Shuttle - Terminal 1 & 2', price: 5000 },
      { no: 'CC-2026-0099', title: 'Airport Shuttle - Terminal 3', price: 5000 },
      { no: 'CC-2026-0100', title: 'Airport Shuttle - Park Area', price: 5000 },
      { no: 'CC-2026-0101', title: 'Airport Shuttle - Terminal 3 -2', price: 5000 },
      { no: 'CC-2026-0102', title: 'National Security of Singapore Agreement - Transportation Project', price: 5000 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0089', 'Corporate Event Transport - Annual Dinner 2026')],
    adjustments: defaultAdjustments,
    payments: [
      { date: '7 Jun 2026', transactionRef: 'TRF-0607', method: 'Bank Transfer', bankAccount: 'David Lim - DBS', amount: 600 },
    ],
    createdOn: '27 Sep 2024, 2:03pm',
    createdBy: 'System',
    lastUpdatedBy: 'Jasmine Tan',
  },
  {
    id: '11',
    invoiceNo: 'ATA-2026-0010',
    customerCode: 'CUST-0015',
    contractTitles: ['Medical Center Route - Buona Vista'],
    dueDate: '01 May 2026',
    status: 'Paid',
    lastUpdatedOn: '10 Apr 2026',
    lastUpdatedAgo: '2 months ago',
    contractGroup: 'Healthcare SG',
    invoiceDate: '1 Mar 2026',
    paymentTerms: '30 Days',
    purchaseOrder: 'PO-2026-077',
    billingCompany: 'HealthGroup',
    accountPayable: 'UOB',
    subTotal: 5500,
    adjustment: 0,
    gst: 440,
    grandTotal: 5940,
    amountReceived: 5940,
    outstandingBalance: 0,
    billingCompanyName: 'National Healthcare Group',
    attention: 'Dr. Lim Wei',
    email: 'lim.wei@nhg.com',
    emailCc: 'procurement@nhg.com',
    sourceContracts: [
      { no: 'CC-2026-0066', title: 'Medical Center Route - Buona Vista', price: 5500 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0066', 'Medical Center Route - Buona Vista')],
    adjustments: [],
    payments: [
      { date: '28 Apr 2026', transactionRef: 'NHG-0428', method: 'Bank Transfer', bankAccount: 'NHG Finance - UOB', amount: 5940 },
    ],
    createdOn: '10 Apr 2026, 9:00am',
    createdBy: 'System',
    lastUpdatedBy: 'Deve Tano',
  },
  {
    id: '12',
    invoiceNo: 'WTA-2026-0009',
    customerCode: 'CUST-0038',
    contractTitles: ['Staff Shuttle - Marina Bay Financial'],
    dueDate: '28 Apr 2026',
    status: 'Paid',
    lastUpdatedOn: '15 Mar 2026',
    lastUpdatedAgo: '3 months ago',
    contractGroup: 'MBS Group',
    invoiceDate: '15 Feb 2026',
    paymentTerms: '45 Days',
    purchaseOrder: 'PO-2026-033',
    billingCompany: 'Marina Bay Sands',
    accountPayable: 'Citibank',
    subTotal: 9000,
    adjustment: 0,
    gst: 720,
    grandTotal: 9720,
    amountReceived: 9720,
    outstandingBalance: 0,
    billingCompanyName: 'Marina Bay Sands Ltd',
    attention: 'Alice Koh',
    email: 'alice.koh@mbs.com',
    emailCc: 'finance@mbs.com',
    sourceContracts: [
      { no: 'CC-2026-0044', title: 'Staff Shuttle - Marina Bay Financial', price: 9000 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0044', 'Staff Shuttle - Marina Bay Financial')],
    adjustments: [],
    payments: [
      { date: '26 Apr 2026', transactionRef: 'MBS-0426', method: 'Bank Transfer', bankAccount: 'MBS Finance - Citi', amount: 9720 },
    ],
    createdOn: '15 Mar 2026, 2:00pm',
    createdBy: 'System',
    lastUpdatedBy: 'Marcus Lim',
  },
  {
    id: '13',
    invoiceNo: 'ATA-2026-0008',
    customerCode: 'CUST-0042',
    contractTitles: ['Airport Shuttle Service - Budget Terminal'],
    dueDate: '22 Apr 2026',
    status: 'Overdue',
    lastUpdatedOn: '20 Feb 2026',
    lastUpdatedAgo: '4 months ago',
    contractGroup: 'Westpoint',
    invoiceDate: '1 Feb 2026',
    paymentTerms: '30 Days',
    purchaseOrder: '-',
    billingCompany: 'Westpoint Rapid',
    accountPayable: 'DBS',
    subTotal: 3600,
    adjustment: 0,
    gst: 288,
    grandTotal: 3888,
    amountReceived: 0,
    outstandingBalance: 3888,
    billingCompanyName: 'APL Shipyard',
    attention: 'Long Chin Kim',
    email: 'Long@apl.com',
    emailCc: 'sales@apl.com',
    sourceContracts: [
      { no: 'CC-2026-0031', title: 'Airport Shuttle Service - Budget Terminal', price: 3600 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0031', 'Airport Shuttle Service - Budget Terminal')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '20 Feb 2026, 11:30am',
    createdBy: 'System',
    lastUpdatedBy: 'Deve Tano',
  },
  {
    id: '14',
    invoiceNo: 'WCA-2026-0007',
    customerCode: 'CUST-0027',
    contractTitles: ['Corporate Retreat Transport - Bintan'],
    dueDate: '15 Apr 2026',
    status: 'Paid',
    lastUpdatedOn: '30 Mar 2026',
    lastUpdatedAgo: '10 weeks ago',
    contractGroup: 'Westpoint',
    invoiceDate: '1 Mar 2026',
    paymentTerms: '30 Days',
    purchaseOrder: 'PO-2026-058',
    billingCompany: 'Westpoint',
    accountPayable: 'DBS',
    subTotal: 11000,
    adjustment: 200,
    gst: 896,
    grandTotal: 12096,
    amountReceived: 12096,
    outstandingBalance: 0,
    billingCompanyName: 'APL Shipyard',
    attention: 'David Lim',
    email: 'david.lim@apl.com',
    emailCc: 'sales@apl.com',
    sourceContracts: [
      { no: 'CC-2026-0038', title: 'Corporate Retreat Transport - Bintan Package', price: 11000 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0038', 'Corporate Retreat Transport - Bintan')],
    adjustments: [],
    payments: [
      { date: '12 Apr 2026', transactionRef: 'WCA-0412', method: 'Bank Transfer', bankAccount: 'APL Finance - DBS', amount: 12096 },
    ],
    createdOn: '30 Mar 2026, 3:00pm',
    createdBy: 'System',
    lastUpdatedBy: 'Jasmine Tan',
  },
  {
    id: '15',
    invoiceNo: 'ATA-2026-0006',
    customerCode: 'CUST-0003',
    contractTitles: ['Daily Commuter Route - Pasir Ris to CBD'],
    dueDate: '10 Apr 2026',
    status: 'Partially Paid',
    lastUpdatedOn: '25 Mar 2026',
    lastUpdatedAgo: '11 weeks ago',
    contractGroup: 'Commute Corp',
    invoiceDate: '1 Feb 2026',
    paymentTerms: '30 Days',
    purchaseOrder: 'PO-2026-021',
    billingCompany: 'Commute Corp',
    accountPayable: 'HSBC',
    subTotal: 3500,
    adjustment: 0,
    gst: 280,
    grandTotal: 3780,
    amountReceived: 1000,
    outstandingBalance: 2780,
    billingCompanyName: 'Commute Corp Pte Ltd',
    attention: 'James Tan',
    email: 'james.tan@commutecorp.com',
    emailCc: 'finance@commutecorp.com',
    sourceContracts: [
      { no: 'CC-2026-0021', title: 'Daily Commuter Route - Pasir Ris to CBD', price: 3500 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0021', 'Daily Commuter Route - Pasir Ris to CBD')],
    adjustments: defaultAdjustments,
    payments: [
      { date: '20 Mar 2026', transactionRef: 'TRF-0320', method: 'Bank Transfer', bankAccount: 'James Tan - HSBC', amount: 1000 },
    ],
    createdOn: '25 Mar 2026, 10:00am',
    createdBy: 'System',
    lastUpdatedBy: 'Marcus Lim',
  },
  {
    id: '16',
    invoiceNo: 'WTA-2026-0003',
    customerCode: 'CUST-0019',
    contractTitles: ['Museum Shuttle - Heritage Trail Circuit'],
    dueDate: '05 Apr 2026',
    status: 'Open',
    lastUpdatedOn: '18 Jan 2026',
    lastUpdatedAgo: '5 months ago',
    contractGroup: 'Heritage SG',
    invoiceDate: '1 Jan 2026',
    paymentTerms: '30 Days',
    purchaseOrder: '-',
    billingCompany: 'National Heritage Board',
    accountPayable: 'UOB',
    subTotal: 4200,
    adjustment: 0,
    gst: 336,
    grandTotal: 4536,
    amountReceived: 0,
    outstandingBalance: 4536,
    billingCompanyName: 'National Heritage Board',
    attention: 'Peter Ho',
    email: 'peter.ho@nhb.gov.sg',
    emailCc: 'heritage@nhb.gov.sg',
    sourceContracts: [
      { no: 'CC-2026-0009', title: 'Museum Shuttle - Heritage Trail Circuit', price: 4200 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0009', 'Museum Shuttle - Heritage Trail Circuit')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '18 Jan 2026, 9:00am',
    createdBy: 'System',
    lastUpdatedBy: 'Deve Tano',
  },
  {
    id: '17',
    invoiceNo: 'ATA-2026-0007',
    customerCode: 'CUST-0008',
    contractTitles: ['Hotel Shuttle - Sentosa Integrated Resort'],
    dueDate: '01 Apr 2026',
    status: 'Open',
    lastUpdatedOn: '12 Feb 2026',
    lastUpdatedAgo: '4 months ago',
    contractGroup: 'Sentosa Resorts',
    invoiceDate: '1 Jan 2026',
    paymentTerms: '30 Days',
    purchaseOrder: 'PO-2026-017',
    billingCompany: 'Resorts World Sentosa',
    accountPayable: 'Standard Chartered',
    subTotal: 8800,
    adjustment: 300,
    gst: 728,
    grandTotal: 9828,
    amountReceived: 0,
    outstandingBalance: 9828,
    billingCompanyName: 'Resorts World Sentosa Pte Ltd',
    attention: 'Helen Goh',
    email: 'helen.goh@rws.com',
    emailCc: 'finance@rws.com',
    sourceContracts: [
      { no: 'CC-2026-0019', title: 'Hotel Shuttle - Sentosa Integrated Resort', price: 8800 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0019', 'Hotel Shuttle - Sentosa Integrated Resort')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '12 Feb 2026, 4:00pm',
    createdBy: 'System',
    lastUpdatedBy: 'Jasmine Tan',
  },
  {
    id: '18',
    invoiceNo: 'WRA-2026-0001',
    customerCode: 'CUST-0015',
    contractTitles: ['School Bus - Raffles Institution'],
    dueDate: '28 Mar 2026',
    status: 'Draft',
    lastUpdatedOn: '5 Jun 2026',
    lastUpdatedAgo: '35 days ago',
    contractGroup: 'Raffles Group',
    invoiceDate: '1 Mar 2026',
    paymentTerms: '60 Days',
    purchaseOrder: 'PO-2026-091',
    billingCompany: 'Raffles Institution',
    accountPayable: 'UOB',
    subTotal: 7200,
    adjustment: 0,
    gst: 576,
    grandTotal: 7776,
    amountReceived: 0,
    outstandingBalance: 7776,
    billingCompanyName: 'Raffles Institution',
    attention: 'VP Admin',
    email: 'admin@ri.edu.sg',
    emailCc: 'finance@ri.edu.sg',
    sourceContracts: [
      { no: 'CC-2026-0055', title: 'School Bus - Raffles Institution Morning', price: 3600 },
      { no: 'CC-2026-0056', title: 'School Bus - Raffles Institution Afternoon', price: 3600 },
    ],
    contractDetails: [makeContractDetail('CC-2026-0055', 'School Bus - Raffles Institution')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '5 Jun 2026, 10:30am',
    createdBy: 'System',
    lastUpdatedBy: 'Marcus Lim',
  },
  {
    id: '19',
    invoiceNo: 'ATA-2026-0003',
    customerCode: 'CUST-0003',
    contractTitles: ['Daily Commuter Route - Clementi to CBD'],
    dueDate: '20 Mar 2026',
    status: 'Draft',
    lastUpdatedOn: '15 May 2026',
    lastUpdatedAgo: '7 weeks ago',
    contractGroup: 'Commute Corp',
    invoiceDate: '15 Dec 2025',
    paymentTerms: '30 Days',
    purchaseOrder: '-',
    billingCompany: 'Commute Corp',
    accountPayable: 'HSBC',
    subTotal: 2900,
    adjustment: 0,
    gst: 232,
    grandTotal: 3132,
    amountReceived: 0,
    outstandingBalance: 3132,
    billingCompanyName: 'Commute Corp Pte Ltd',
    attention: 'James Tan',
    email: 'james.tan@commutecorp.com',
    emailCc: 'finance@commutecorp.com',
    sourceContracts: [
      { no: 'CC-2025-0422', title: 'Daily Commuter Route - Clementi to CBD', price: 2900 },
    ],
    contractDetails: [makeContractDetail('CC-2025-0422', 'Daily Commuter Route - Clementi to CBD')],
    adjustments: defaultAdjustments,
    payments: [],
    createdOn: '15 May 2026, 8:00am',
    createdBy: 'System',
    lastUpdatedBy: 'Deve Tano',
  },
]
